import type { NextPage } from "next";
import Head from "next/head";
import { styled } from "../stitches.config";
import { usePrimaryColor } from "../components/PrimaryColor";
import Title from "../components/Title";
import ToggleColors from "../components/ToggleColors";
import ToggleColorMode from "../components/ToggleColorMode";

const Content = styled("div", {
  width: "100%",
  height: "100vh",
  display: "grid",
  placeItems: "center",
});

const Text = styled("p", {
  fontSize: 24,
});

const Strong = styled("strong", {});

const Home: NextPage = () => {
  const { primaryColor } = usePrimaryColor()!;

  return (
    <Content>
      <Head>
        <title>Stitches Dynamic Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
      <ToggleColorMode />
      <ToggleColors />
      <Text>
        The current primary color is:{" "}
        <Strong css={{ color: `$primary` }}>{primaryColor}</Strong>
      </Text>
    </Content>
  );
};

export default Home;
